### ISSUE TITLE
Errors in Evaluation

### ISSUE THREAD

**Issue by yangzm11** [tianrang-intelligence/TSCC2019#2]
When trying to run evaluation with the given sample code as following:

`python3 evaluate.py --scenario "hangzhou_bc_tyc_1h_7_8_1848" --num_step 3600`

Some errors occur:

Time: 100.0 / 3600
Time: 200.0 / 3600
Time: 300.0 / 3600
Time: 400.0 / 3600
Time: 500.0 / 3600
Time: 600.0 / 3600
Time: 700.0 / 3600
Time: 800.0 / 3600
Time: 900.0 / 3600
Time: 1000.0 / 3600
Time: 1100.0 / 3600
Time: 1200.0 / 3600
Time: 1300.0 / 3600
Time: 1400.0 / 3600
Time: 1500.0 / 3600
Time: 1600.0 / 3600
Time: 1700.0 / 3600
Time: 1800.0 / 3600
Time: 1900.0 / 3600
Time: 2000.0 / 3600
Time: 2100.0 / 3600
Time: 2200.0 / 3600
Time: 2300.0 / 3600
Time: 2400.0 / 3600
Time: 2500.0 / 3600
Time: 2600.0 / 3600
Time: 2700.0 / 3600
Time: 2800.0 / 3600
Time: 2900.0 / 3600
Time: 3000.0 / 3600
Time: 3100.0 / 3600
Time: 3200.0 / 3600
Time: 3300.0 / 3600
Time: 3400.0 / 3600
Time: 3500.0 / 3600
Time: 3600.0 / 3600
Traceback (most recent call last):
  File "evaluate.py", line 147, in <module>
    main()
  File "evaluate.py", line 21, in main
    evaluate_one_traffic(sim_setting, args.scenario)
  File "evaluate.py", line 31, in evaluate_one_traffic
    tt = cal_travel_time(dic_sim_setting, roadnetFile, flowFile, planFile)
  File "evaluate.py", line 66, in cal_travel_time
    return eng.get_score()
AttributeError: 'engine.Engine' object has no attribute 'get_score'

It seems that 'engine' does not have the function of 'get_score'.

PS 'engine' seems to be a part of CityFlow, the source file is [engine](https://github.com/cityflow-project/CityFlow/blob/master/src/engine/engine.cpp)

**Comment by yangzm11** [comment]
#

**Comment by zxsRambo** [comment]
Hi, I'm sorry for not noticing your issue to this day and some unnecessary inconvenience. This issue is caused by the outdated 'engine' which does not have the 'get_score' API, in the pre-prepared docker image in Docker Hub, Google Drive and Baidu Yun. We have updated these images and you just can use one of them to fix this bug.

Additionally, 'engine' is equivalent to CityFlow, except for the name and some other minor differences. You can feel relieved to use 'engine' as the simulator.

**Comment by zxsRambo** [comment]
Hi, I'm sorry for not noticing your issue to this day and some unnecessary inconvenience. This issue is caused by the outdated 'engine' which does not have the 'get_score' API, in the pre-prepared docker image placed in Docker Hub, Google Drive and Baidu Yun. We have updated these images and you can just use one of them to fix this bug.

Additionally, 'engine' is equivalent to CityFlow, except for the name and some other minor differences. You can feel relieved to use 'engine' as the simulator in this competition.

**Comment by yangzm11** [comment]
Great! The issue has been solved. It runs well with the latest docker image. 

Thanks O(∩_∩)O
